name: Inject Firebase Config and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject Firebase Config
        run: |
          echo "const firebaseConfig = process.env.FIREBASE_CONFIG; export default firebaseConfig;" > firebaseConfig.js

